version: "2"
linters:
  default: none
  enable:
    - sloglint
  settings:
    sloglint:
      # Enforce using attributes only (overrides no-mixed-args, incompatible with kv-only).
      # https://github.com/go-simpler/sloglint?tab=readme-ov-file#attributes-only
      # Default: false
      attr-only: true
      # Enforce using methods that accept a context.
      # Values:
      # - "": disabled
      # - "all": report all contextless calls
      # - "scope": report only if a context exists in the scope of the outermost function
      # https://github.com/go-simpler/sloglint?tab=readme-ov-file#context-only
      # Default: ""
      context: "all"
      forbidden-keys:
        - time
        - level
        - msg
        - source
        - foo
      args-on-sep-lines: true